<a href="https://colab.research.google.com/github/Letch49/ML_vvsu_2024/blob/master/lab1/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл

**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/global-data-on-sustainable-energy.csv')
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам

In [5]:
df.columns

Index(['Entity', 'Year', 'Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable-electricity-generating-capacity-per-capita',
       'Financial flows to developing countries (US $)',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country',
       'Renewables (% equivalent primary energy)', 'gdp_growth',
       'gdp_per_capita', 'Density\n(P/Km2)', 'Land Area(Km2)', 'Latitude',
       'Longitude'],
      dtype='object')

In [6]:
df.head(5)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [7]:
df[-5:]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.00046,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.00015,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.00011,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.00023,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [8]:
df.describe()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
count,3649.000000,3639.000000,3480.000000,2718.000000,1.560000e+03,3455.000000,3628.000000,3523.000000,3628.000000,3607.000000,3649.000000,3442.000000,3.221000e+03,1512.000000,3332.000000,3367.000000,3.648000e+03,3648.000000,3648.000000
mean,2010.038367,78.933702,63.255287,113.137498,9.422400e+07,32.638165,70.365003,13.450190,23.968010,36.801182,25743.981745,5.307345,1.598665e+05,11.986707,3.441610,13283.774348,6.332135e+05,18.246388,14.822695
std,6.054228,30.275541,39.043658,244.167256,2.981544e+08,29.894901,348.051866,73.006623,104.431085,34.314884,34773.221366,3.532020,7.736611e+05,14.994644,5.686720,19709.866716,1.585519e+06,24.159232,66.348148
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,1.000000e+01,0.000000,-62.075920,111.927225,2.100000e+01,-40.900557,-175.198242
25%,2005.000000,59.800890,23.175000,3.540000,2.600000e+05,6.515000,0.290000,0.000000,0.040000,2.877847,3116.737300,3.170000,2.020000e+03,2.137095,1.383302,1337.813437,2.571300e+04,3.202778,-11.779889
50%,2010.000000,98.361570,83.150000,32.910000,5.665000e+06,23.300000,2.970000,0.000000,1.470000,27.865068,13120.570000,4.300000,1.050000e+04,6.290766,3.559855,4578.633208,1.176000e+05,17.189877,19.145136
75%,2015.000000,100.000000,100.000000,112.210000,5.534750e+07,55.245000,26.837500,0.000000,9.600000,64.403792,33892.780000,6.027500,6.058000e+04,16.841638,5.830099,15768.615365,5.131200e+05,38.969719,46.199616
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,96.040000,5184.130000,809.410000,2184.940000,100.000010,262585.700000,32.570000,1.070722e+07,86.836586,123.139555,123514.196700,9.984670e+06,64.963051,178.065032

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета



1.   **Ответ 1.** 2010.038367	78.933702	63.255287	113.137498	9.422400e+07	32.638165	70.365003	13.450190	23.968010	36.801182	25743.981745	5.307345	1.598665e+05	11.986707	3.441610	13283.774348	6.332135e+05	18.246388	14.822695
2.   **Ответ 2.** **min** 2000.000000	1.252269	0.000000	0.000000	0.000000e+00	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	0.110000	1.000000e+01	0.000000	-62.075920	111.927225	2.100000e+01	-40.900557	-175.198242

**max** 2020.000000	100.000000	100.000000	3060.190000	5.202310e+09	96.040000	5184.130000	809.410000	2184.940000	100.000010	262585.700000	32.570000	1.070722e+07	86.836586	123.139555	123514.196700	9.984670e+06	64.963051	178.065032

##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [11]:
df['Entity'] = df['Entity'].astype('category')
df['Year'] = df['Year'].astype(int)
df['Renewable-electricity-generating-capacity-per-capita'] = df['Renewable-electricity-generating-capacity-per-capita'].astype(float)
#Вывести типы колонок тут
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   category
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: category(1), float64(18), int64(1), object(1)
memory usage: 582.9+ KB

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?
Ответ. Entity - категориальный, year - кол-ные, Latitude - кол-ные

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [13]:
df.loc[df['Latitude'] > 24]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.20,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.20,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.20,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.50,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.90,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3560,Uzbekistan,2016,100.000000,85.20,59.88,690000.0,1.61,48.75,0.0,7.25,...,16374.34200,7.82,105230.003400,3.567936,5.932151,2704.677188,79,447400.0,41.377491,64.585262
3561,Uzbekistan,2017,100.000000,84.90,58.24,60130000.0,1.75,49.71,0.0,8.35,...,16642.67600,7.88,109529.998800,3.972285,4.395275,1916.764642,79,447400.0,41.377491,64.585262
3562,Uzbekistan,2018,100.000000,84.30,59.09,84130000.0,1.49,53.58,0.0,5.85,...,16445.74000,9.05,112470.001200,2.927033,5.354997,1597.068337,79,447400.0,41.377491,64.585262
3563,Uzbekistan,2019,100.000000,84.60,57.96,65940000.0,1.57,53.64,0.0,6.47,...,16212.22100,8.37,116709.999100,3.197033,5.709632,1784.009816,79,447400.0,41.377491,64.585262
3564,Uzbekistan,2020,100.000000,84.25,60.02,NaN,NaN,50.93,0.0,5.01,...,15860.60900,NaN,NaN,2.523421,1.714771,1750.697113,79,447400.0,41.377491,64.585262

In [17]:
df.loc[df['Year'] >= 2019]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
19,Afghanistan,2019,97.700000,31.9,9.58,4620000.0,18.51,0.18,0.0,0.89,...,802.61255,2.41,6079.999924,NaN,3.911603,494.179350,60,652230.0,33.939110,67.709953
20,Afghanistan,2020,97.700000,33.2,9.35,NaN,NaN,0.12,0.0,0.68,...,702.88800,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0,33.939110,67.709953
40,Albania,2019,100.000000,80.7,NaN,NaN,NaN,0.00,0.0,5.17,...,11585.55500,2.50,4829.999924,NaN,2.113420,5395.659532,105,28748.0,41.153332,20.168331
41,Albania,2020,100.000000,81.3,NaN,NaN,NaN,0.00,0.0,5.31,...,11158.00300,NaN,NaN,NaN,-3.955398,5246.292306,105,28748.0,41.153332,20.168331
61,Algeria,2019,99.500000,99.7,15.93,60000.0,0.16,75.85,0.0,0.84,...,16259.05300,5.32,171250.000000,0.294747,1.000000,3989.668276,18,2381741.0,28.033886,1.659626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3606,Yemen,2020,73.757930,61.5,8.48,NaN,NaN,2.74,0.0,0.49,...,1092.00210,NaN,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3626,Zambia,2019,43.000000,11.2,142.11,78570000.0,84.50,2.05,0.0,12.62,...,2983.88160,7.09,6800.000191,NaN,1.441306,1305.001031,25,752618.0,-13.133897,27.849332
3627,Zambia,2020,44.524475,10.4,138.23,NaN,NaN,2.00,0.0,13.10,...,3099.08300,NaN,NaN,NaN,-2.785055,985.132436,25,752618.0,-13.133897,27.849332
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [18]:
df.loc[df['Entity'] == 'Yemen']

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3586,Yemen,2000,49.187256,55.70,0.00,1480000.0,0.95,3.21,0.0,0.00,...,3228.2104,2.823132,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3587,Yemen,2001,50.341240,56.10,0.00,30000.0,0.89,3.42,0.0,0.00,...,3380.4053,3.016477,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3588,Yemen,2002,51.487637,56.70,0.00,0.0,0.90,3.54,0.0,0.00,...,3320.3242,2.811401,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3589,Yemen,2003,52.628803,57.15,0.00,NaN,0.78,3.85,0.0,0.00,...,3707.2222,3.010832,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3590,Yemen,2004,49.590000,57.40,0.00,110000.0,0.75,4.10,0.0,0.00,...,3811.3972,3.160727,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3591,Yemen,2005,54.904820,57.90,0.00,140000.0,0.74,4.48,0.0,0.00,...,3906.3083,3.188304,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3592,Yemen,2006,55.800335,58.20,0.00,130000.0,0.76,5.06,0.0,0.00,...,3788.2456,3.308474,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3593,Yemen,2007,57.188570,58.70,0.00,110000.0,0.76,5.67,0.0,0.00,...,3902.2861,3.133247,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3594,Yemen,2008,58.339930,59.00,0.04,150000.0,0.74,6.15,0.0,0.00,...,3976.8901,3.176676,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3595,Yemen,2009,59.501240,59.50,0.04,11170000.0,0.70,6.34,0.0,0.00,...,4277.2236,3.380211,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3596,Yemen,2010,60.675194,59.70,0.04,310000.0,0.78,7.29,0.0,0.00,...,4030.7585,3.165451,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3597,Yemen,2011,61.864506,60.00,0.05,NaN,0.93,5.83,0.0,0.00,...,3289.4512,3.161177,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3598,Yemen,2012,52.410000,60.00,0.06,79630000.0,1.08,6.65,0.0,0.00,...,2769.0400,2.790347,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3599,Yemen,2013,75.600000,60.30,0.09,660000.0,0.76,7.99,0.0,0.00,...,3797.8290,3.693557,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3600,Yemen,2014,66.100000,60.80,0.19,18670000.0,0.76,7.19,0.0,0.01,...,3495.3290,3.211405,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3601,Yemen,2015,67.310930,61.10,2.26,NaN,1.96,5.81,0.0,0.12,...,1837.1029,2.050356,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3602,Yemen,2016,68.859505,61.20,2.94,NaN,2.48,4.36,0.0,0.16,...,1432.5522,NaN,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3603,Yemen,2017,79.200000,61.35,3.59,10000.0,2.80,3.63,0.0,0.19,...,1288.8767,NaN,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3604,Yemen,2018,62.000000,61.50,8.77,55730000.0,3.60,2.82,0.0,0.48,...,1170.7261,NaN,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3605,Yemen,2019,72.751076,61.30,8.57,1200000.0,3.11,2.93,0.0,0.48,...,1475.9852,NaN,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3606,Yemen,2020,73.757930,61.50,8.48,NaN,NaN,2.74,0.0,0.49,...,1092.0021,NaN,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [20]:
df.groupby('Entity').mean()

<ipython-input-20-8223fa95397a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Entity').mean()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
Entity,,,,,,,,,,,,,,,,,,,
Afghanistan,2010.0,52.520488,19.802381,8.581429,3.296947e+07,25.6805,0.189524,0.0,0.740952,78.872636,697.268136,2.039000,4073.000025,NaN,6.163893,439.055765,652230.0,33.939110,67.709953
Albania,2010.0,99.981429,63.592857,NaN,NaN,NaN,0.048571,0.0,5.184286,98.855430,11353.520929,3.177500,4303.000004,NaN,3.859305,3623.224775,28748.0,41.153332,20.168331
Algeria,2010.0,99.108146,98.904762,9.390000,5.056250e+05,0.2870,46.895714,0.0,0.365238,0.742125,12925.532952,4.498500,119921.000066,0.185239,2.885714,3787.817377,2381741.0,28.033886,1.659626
Angola,2010.0,35.138564,44.933333,43.951429,9.525000e+06,57.6970,2.040476,0.0,4.420952,68.980548,3102.008457,2.896500,21689.499863,NaN,4.945895,2982.568601,1246700.0,-11.202692,17.873887
Antigua and Barbuda,2010.0,98.823761,100.000000,22.455238,9.700000e+06,0.2005,0.271429,0.0,0.002857,0.861557,32065.486190,3.624000,512.999998,NaN,1.515946,13555.401528,443.0,17.060816,-61.796428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,2010.0,99.848840,84.976190,61.972381,5.868556e+07,1.2385,43.476667,0.0,6.438095,12.974661,19346.599286,15.948500,118427.000704,3.192610,6.253772,1438.250604,447400.0,41.377491,64.585262
Vanuatu,2010.0,41.269784,12.050000,19.339524,5.694000e+06,43.6560,0.046667,0.0,0.008095,11.904762,2471.556643,3.516500,122.999999,NaN,2.441195,2458.898510,12189.0,-15.376706,166.959158
Yemen,2010.0,60.928522,59.290476,1.672381,1.059562e+07,1.3115,4.907619,0.0,0.091905,2.593720,2998.960281,3.067611,NaN,NaN,NaN,NaN,527968.0,15.552727,48.516388
Zambia,2010.0,27.753585,14.471429,146.577619,1.881594e+08,86.8955,0.492381,0.0,10.701429,96.479406,3027.719648,9.181500,3559.000016,NaN,5.442444,1144.799404,752618.0,-13.133897,27.849332
Zimbabwe,2010.0,39.172120,30.930952,66.068571,2.651154e+07,79.1500,3.229048,0.0,5.007143,60.849178,3825.827057,11.474762,11040.000110,NaN,0.132669,916.669430,390757.0,-19.015438,29.154857

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация